language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coveralls

script:
  - coverage run --source gorilla -m unittest discover -s tests -v

after_success:
  - coveralls
